# EchoDB configs

# server related configs
server:
  host: "0.0.0.0"
  port: 6380

# persistence related configs
persistence:
  enabled: true
  data_dir: "./data"
  aof:
    enabled: true
    file: "echo.aof"
    sync_mode: "periodic"
    flush_interval: "5s"
